wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1677487693.566536
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      3:
      - 23
      4: 3.10.8
      5: 0.13.10
      8:
      - 1
      - 5
